In [1]:
from datetime import date, timedelta, datetime
from dateutil.relativedelta import relativedelta
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
# Read CSV file for job ids
stations = pd.read_csv("station.csv")
stations.head()

,id,name,lat,long,dock_count,city,installation_date
0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,San Jose,8/6/2013
1,3,San Jose Civic Center,37.330698,-121.888979,15,San Jose,8/5/2013
2,4,Santa Clara at Almaden,37.333988,-121.894902,11,San Jose,8/6/2013
3,5,Adobe on Almaden,37.331415,-121.893200,19,San Jose,8/5/2013
4,6,San Pedro Square,37.336721,-121.894074,15,San Jose,8/7/2013

In [12]:
df = stations.groupby(['city'])
df.head()

,id,name,lat,long,dock_count,city,installation_date
0,2,San Jose Diridon Caltrain Station,37.329732,-121.901782,27,San Jose,8/6/2013
1,3,San Jose Civic Center,37.330698,-121.888979,15,San Jose,8/5/2013
2,4,Santa Clara at Almaden,37.333988,-121.894902,11,San Jose,8/6/2013
3,5,Adobe on Almaden,37.331415,-121.893200,19,San Jose,8/5/2013
4,6,San Pedro Square,37.336721,-121.894074,15,San Jose,8/7/2013
14,21,Franklin at Maple,37.481758,-122.226904,15,Redwood City,8/12/2013
15,22,Redwood City Caltrain Station,37.486078,-122.232089,25,Redwood City,8/15/2013
16,23,San Mateo County Center,37.487616,-122.229951,15,Redwood City,8/15/2013
17,24,Redwood City Public Library,37.484219,-122.227424,15,Redwood City,8/12/2013
18,25,Stanford in Redwood City,37.485370,-122.203288,15,Redwood City,8/12/2013
20,27,Mountain View City Hall,37.389218,-122.081896,15,Mountain View,8/16/2013
21,28,Mountain View Caltrain Station,37.394358,-122.076713,23,Mountain View,8/15/2013
22,29,San Antonio Caltrain Station,37.406940,-122.106758,23,Mountain View,8/15/2013
23,30,Evelyn Park and Ride,37.390277,-122.066553,15,Mountain View,8/16/2013
24,31,San Antonio Shopping Center,37.400443,-122.108338,15,Mountain View,12/31/2013
27,34,Palo Alto Caltrain Station,37.443988,-122.164759,23,Palo Alto,8/14/2013
28,35,University and Emerson,37.444521,-122.163093,11,Palo Alto,8/15/2013
29,36,California Ave Caltrain Station,37.429082,-122.142805,15,Palo Alto,8/14/2013
30,37,Cowper at University,37.448598,-122.159504,11,Palo Alto,8/14/2013
31,38,Park at Olive,37.425684,-122.137777,15,Palo Alto,8/14/2013
32,41,Clay at Battery,37.795001,-122.399970,15,San Francisco,8/19/2013
33,42,Davis at Jackson,37.797280,-122.398436,15,San Francisco,8/19/2013
34,45,Commercial at Montgomery,37.794231,-122.402923,15,San Francisco,8/19/2013
35,46,Washington at Kearney,37.795425,-122.404767,15,San Francisco,8/19/2013
36,47,Post at Kearney,37.788975,-122.403452,19,San Francisco,8/19/2013

In [29]:
sf = stations.loc[stations['city'] == 'San Francisco']
sf.head()

,id,name,lat,long,dock_count,city,installation_date
32,41,Clay at Battery,37.795001,-122.399970,15,San Francisco,8/19/2013
33,42,Davis at Jackson,37.797280,-122.398436,15,San Francisco,8/19/2013
34,45,Commercial at Montgomery,37.794231,-122.402923,15,San Francisco,8/19/2013
35,46,Washington at Kearney,37.795425,-122.404767,15,San Francisco,8/19/2013
36,47,Post at Kearney,37.788975,-122.403452,19,San Francisco,8/19/2013

In [30]:
sf['name'].unique()

array(['Clay at Battery', 'Davis at Jackson', 'Commercial at Montgomery',
       'Washington at Kearney', 'Post at Kearney',
       'Embarcadero at Vallejo', 'Spear at Folsom',
       'Harry Bridges Plaza (Ferry Building)', 'Embarcadero at Folsom',
       'Powell Street BART', 'Embarcadero at Bryant',
       'Temporary Transbay Terminal (Howard at Beale)', 'Beale at Market',
       '5th at Howard', 'San Francisco City Hall', 'Golden Gate at Polk',
       'Embarcadero at Sansome', '2nd at Townsend', '2nd at Folsom',
       'Howard at 2nd', '2nd at South Park', 'Townsend at 7th',
       'South Van Ness at Market', 'Market at 10th',
       'Yerba Buena Center of the Arts (3rd @ Howard)',
       'San Francisco Caltrain 2 (330 Townsend)',
       'San Francisco Caltrain (Townsend at 4th)',
       'Powell at Post (Union Square)',
       'Civic Center BART (7th at Market)',
       'Grant Avenue at Columbus Avenue', 'Steuart at Market',
       'Mechanics Plaza (Market at Battery)', 'Market at 4th',
       'Market at Sansome', 'Broadway St at Battery St'], dtype=object)

In [ ]:
redwoodcity =